# Generated by Django 4.2.1 on 2023-05-28 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('work_order_number', models.CharField(max_length=50, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('finished_at', models.DateTimeField(auto_now=True, null=True)),
                ('work_type', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Maid Request', 'Maid Request'), ('Technician Request', 'Technician Request'), ('Amenity Request', 'Amenity Request')], max_length=50)),
                ('work_status', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancel', 'Cancel')], max_length=50)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_order',
            },
        ),
        migrations.CreateModel(
            name='AmenityRequest',
            fields=[
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pms.workorder')),
                ('amenity_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'amenity_request',
            },
        ),
        migrations.CreateModel(
            name='MaidRequest',
            fields=[
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pms.workorder')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'maid_request',
            },
        ),
        migrations.CreateModel(
            name='TechnicianRequest',
            fields=[
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pms.workorder')),
                ('defect_type', models.CharField(choices=[('Electricity', 'Electricity'), ('Air Con', 'Air Con'), ('Plumbing', 'Plumbing'), ('Internet', 'Internet')], max_length=50)),
            ],
            options={
                'db_table': 'technician_request',
            },
        ),
    ]
