# Generated by Django 4.2.1 on 2023-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
